[settings]
timeout = 1000

[relaychain]
default_image = "paritypr/polkadot-debug:master"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = 9944

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "dave"

[[parachains]]
id = 1000

  [[parachains.collators]]
  name = "collator1000-01"
  command = "test-node"
  ws_port = 9948

  [[parachains.collators]]
  name = "collator1000-02"
  command = "test-node"
  # container chain collators are also orchestrator chain collators
  [[parachains.collators]]
  name = "collator2000-01"
  command = "test-node"
  args = ["-- --tmp --ws-port 9949 --chain container-chain-2000.json"]

  [[parachains.collators]]
  name = "collator2000-02"
  command = "test-node"
  args = ["-- --tmp --chain container-chain-2000.json"]

  [[parachains.collators]]
  name = "collator2001-01"
  command = "test-node"
  args = ["-- --tmp --ws-port 9950 --chain container-chain-2001.json"]

  [[parachains.collators]]
  name = "collator2001-02"
  command = "test-node"
  args = ["-- --tmp --chain container-chain-2001.json"]

[[parachains]]
id = 2000

  [[parachains.collators]]
  name = "Collator2000-01"
  command = "test-node"

  [[parachains.collators]]
  name = "Collator2000-02"
  command = "test-node"

[[parachains]]
id = 2001

  [[parachains.collators]]
  name = "Collator2001-01"
  command = "test-node"

  [[parachains.collators]]
  name = "Collator2001-02"
  command = "test-node"
