name: CI

on: ["pull_request"]

jobs:

  ####### Building and Testing binaries #######

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        run: rustup show

      - name: Formatter
        run: cargo fmt --all --check

      - name: Build
        run: cargo build --release --all

      - name: Test
        run: cargo test --release --all
      
      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Node  
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          cache-dependency-path: test/pnpm-lock.yaml
      
      - name: "Install and run upgrade test"
        run: |
          cd test
          pnpm i
          pnpm moonwall test dev_tanssi